-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgs/H4ALLy080QMWZJ
dkk3/bIDRAEkwLDmJitJtt9kXsOgCgYIKoZIzj0DAQehRANCAAQesHsB1Nrih9cI
eNVhPFKfKKqkrD9RkmH4HbQT4VWSMLiIQM0hjbz0+7Ka2nahmjxBO6wHWuqh2O4v
8xTDJsbk
-----END PRIVATE KEY-----